### ISSUE TITLE
No Host Specified in URI error

### ISSUE THREAD

**Issue by OceanManta** [ignertic/paynow#11]
l think you are the one who needs to provide that URL in the package perhaps hiding it from us using a json file or something. l dont see anywhere where l can put this URL also l dont have any URL or URI since lm running off a mobile Application,
Also The issue maybe related to the fact that the pollURL is not being return by paynow. (judging by the definition of the varable pollURL in paynow.dart). OR it could be that it is being returned but not being assigned to the same pollURL variable or the correct reference idk just try checking.

This is my files in my class.
![image](https://user-images.githubusercontent.com/50319585/117821868-47751680-b26c-11eb-8741-b8568f0ba146.png)

This is the paynow.dart plugin class
![image](https://user-images.githubusercontent.com/50319585/117821936-58be2300-b26c-11eb-916e-fe220f9f86fc.png)

**Comment by ignertic** [comment]
I'll look into this

**Comment by ignertic** [comment]
Hello @OceanManta . 

Unfortunately I'm failing to reproduce your problem but I have noticed that no pollUrl is being printed at line 44 of your code.
Are your keys live because it seems you're not receiving the pollUrl from paynow?

I will also look into how I can do all this under the hood in the next update

**Comment by OceanManta** [comment]
Okay l understand, Sorry about it. How do l check if the Keys are active?

**Comment by ignertic** [comment]
> Okay l understand, Sorry about it. How do l check if the Keys are active?

Confirm with Paynow Support Team. If they are live then please feel free to reopen this issue :)

**Comment by OceanManta** [comment]
Thanks @ignertic ndokukandira eco manje manje
