### ISSUE TITLE
package failing in flutter web

### ISSUE THREAD

**Issue by asimbo** [ignertic/paynow#2]
I am trying to use the paynow gateway using the package. How ever I am getting the following errors

Access to fetch at 'https://www.paynow.co.zw/interface/remotetransaction' from origin 'mywebsite' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The FetchEvent for "https://www.paynow.co.zw/interface/remotetransaction" resulted in a network error response: the promise was rejected.

**Comment by ignertic** [comment]
I ran the paynow example, Express Checkout seems to be working fine so sending requests has no issues. I'll look closely into the headers problem

**Comment by ignertic** [comment]
I guess because paynow sends a request to a different domain. So the browser is blocking it as it usually allows a request in the same origin for security reasons

**Comment by ignertic** [comment]
Workaround would be to use the plugin https://pub.dev/packages/flutter_webview_plugin
