### ISSUE TITLE
No Host specified in URI Exception

### ISSUE THREAD

**Issue by OceanManta** [ignertic/paynow#4]
lm getting this No host specified in URI issue when l use this with flutter in a mobile application. 
the error occurs on the line paynow.checkTransactionStatus(pollUrl) 

Between the paynow and the dot is where the error occurs. How can l fix this?

![Screenshot 2021-02-24 141742](https://user-images.githubusercontent.com/50319585/109113362-d4680380-7744-11eb-88ed-4576e453b85f.png)
![Screenshot 2021-02-24 141913](https://user-images.githubusercontent.com/50319585/109113368-d5993080-7744-11eb-8999-4781d6bb23a2.png)

**Comment by DonnC** [comment]
I think this is because, pollUrl is null or empty can u first print poll url first

**Comment by OceanManta** [comment]
thanks, lm running it now to check, What do l do if it is null?

**Comment by DonnC** [comment]
First check if `response.status` returns `true` then proceed to check transaction status, if `false` you may print the `response.error` found and initiate the process again

**Comment by OceanManta** [comment]
l had upgraded to dart 2 with the new release. So my paynow package is yet to receive the update for dart two it no longer works with this version of dart.

**Comment by DonnC** [comment]
Okay that will be another `issue`  to open, i hope he is already working on it

**Comment by OceanManta** [comment]
Should l open it or do you want to?

**Comment by DonnC** [comment]
you can open since you have the latest version
in the mean time you can check this `PR` #7

**Comment by OceanManta** [comment]
Okay Perfect
