### ISSUE TITLE
Return paynowreference

### ISSUE THREAD

**Issue by DonnC** [ignertic/paynow#6]
@ignertic  Looking at the model `StatusResponse` its `reference` does not correspond to a traceable paynow reference given as `paynowreference` when you open `pollUrl` with browser
`reference=asf&paynowreference=11525925&amount=1.50&status=Cancelled&pollurl=h...`
The plugin just returns `reference` as `asf`. Please any way to get the actual `paynowreference` as when you open pollurl with brower for reconcilliation purposes on certain transactions

**Comment by ignertic** [comment]
I hear you, I'm still waiting for the pending PRs to be merged. In the meantime I'll look into the effects of this

**Comment by DonnC** [comment]
I have forked and made changes and it worked well, if its fine i can open a PR

**Comment by DonnC** [comment]
#7
