### ISSUE TITLE
Http version update

### ISSUE THREAD

**Issue by OceanManta** [ignertic/paynow#9]
`Dart 2` is working with `HTTP version 13.` l recently updated to `dart 2` because most of the flutter plugins use this feature now. if possible can we get an update to the package's `http version`. The current one that was updated `April 23 2021` is not compatible with the newer `Dart version`. You can probably do this in the `pubspec.yaml` 
![image](https://user-images.githubusercontent.com/50319585/116855213-4e12e680-abf9-11eb-987d-a150a3d099fd.png)

@ignertic 
 @DonnC

**Comment by ignertic** [comment]
Closing this with https://github.com/ignertic/paynow/pull/10
